apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-auth-proxy
  namespace: mcp-auth-proxy
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      terminationGracePeriodSeconds: 150
      containers:
        - name: mcp-auth-proxy
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "256Mi"
