version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - gocritic
    - gosec
    - misspell
    - noctx
    - revive
    - unconvert
  settings:
    gosec:
      excludes:
        - G104  # errcheck dupe
    revive:
      rules:
        - name: exported
          disabled: true

run:
  timeout: 5m
